#+title: Operating System                                   
For the development of open source software we also want to use open source
software. Therefore we choosed to describe the procedures on the basis of Linux.
We use Ubuntu, other distributions should behave similarly.
* The terminal
In the past you communicated with a computer via a terminal. This is like a
typewriter with a screen. You type commands and get an output on the screen.
We're going to run into this concept a lot more. It is, if you get used to it,
a very flexible way to tell the machine what you want it to do for you.

Today's user often only knows the GUI (Graphical User Interface) to communicate
with programs on the machine. But we use a terminal and use a terminal emulation
program which gives us input and output in a window.
We can find such a program in the menu ~System Tools -> QTerminal~.

With this program we can even keep several terminal sessions open in parallel
(~<Ctrl+Shift+Tab>~ creates an additional session).

* The Shell
The program which processes our input and returns something to us is called the
shell. In our case this is concretely the Bash (Bourne Again Shell)
which is mostly configured by default.

You should learn how to move around in the file system with simple commands (~cd~),
copy (~cp~), delete (~rm~), move (~mv~) and display (~less~) files.

It is worth mentioning that the last entered commands can be retrieved with the
upward pointing cursor key (arrow).
You can also change them for the next execution.

Furthermore the tabulator key
is a valuable companion, with it you can complete commands or file names.
This saves a lot of typing and protects against typos.

* Install programs
For the installation of programs, in this context also called packages, we use 
package managers like ~apt~ and ~snap~. While ~apt~
offers software versions that integrate well into the Linux distribution,
it is also possible to install newer versions with ~snap~, which we will use
to make use of.

